# Set the prefix key to Ctrl-a
set -g prefix C-a

# Enable RGB colors for certain terminals
set -as terminal-features ",alacritty:RGB"

# Set the history limit
set -g history-limit 100000

# Set the external copy command to integrate with system clipboard
set -s copy-command 'pbcopy'
set -s set-clipboard off

# Vi mode
set -g mode-keys vi
set -g status-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel

# incremental search
bind-key -T copy-mode-vi / command-prompt -i -I "#{pane_search_string}" -p "(search down)" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -I "#{pane_search_string}" -p "(search up)" "send -X search-backward-incremental \"%%%\""

set -g mouse on

set -g escape-time 10
set -g focus-events on
